
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import TclError, ttk
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\n\Downloads\proj\proj\assets")

Pizzadough_list = ["Soft Crust Pizza","Crust Pizza"]   
Topping_list = ["Seafood","Tom Yum Kung","Hawaiian","Double Cheese","Spicy Seafood","Cheese & Bacon","Classic Mushroom"]
Addtopping_list = ["Mozzarella Cheese","Bacon Bits","Mushrooms","Prawn","Seafood","Red & Green Chilli","Tomato"]
Drink_list = ["Mineral Water","Beer","Cola","Soda","Orange juice","Watermelon"]
total_detail={'Soft Crust Pizza':150,'Crust Pizza':150,'Mozzarella Cheese':25,'Bacon Bits':40,'Mushrooms':15,'Prawn':20,'Seafood':40,'Tomato':10
              ,'Mineral Water':15,'Beer':50,'Cola':25,'Soda':15,'Orange juice':30,'Watermelon':30}


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def create_input_frame(container):
    frame = ttk.Frame(container)
    # grid layout for the input frame
    frame.columnconfigure(0, weight=1)
    frame.columnconfigure(1, weight=3)

    # สร้าง combo box เพื่อแสดงรายการรหัสวิชาให้เลือก
    ttk.Label(frame, text='รหัสวิชา:').grid(column=0, row=0, sticky=tk.W)
    cbo_id = ttk.Combobox(frame, width=20, textvariable=selected_id)

    cbo_id['values'] = Pizzadough_list
    cbo_id['state'] = 'readonly'  # prevent typing a value
    cbo_id.focus()
    cbo_id.grid(column=1, row=0, sticky=tk.W)

    # bind the selected value change
    # ถ้ามีการเลือก Combpbox ให้เรียก Function  id_changed
    cbo_id.bind('<<ComboboxSelected>>', id_changed)









window = Tk()

window.geometry("369x515")
window.configure(bg = "#001DBA")


canvas = Canvas(
    window,
    bg = "#001DBA",
    height = 515,
    width = 369,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    184.0,
    257.0,
    image=image_image_1
)

canvas.create_rectangle(
    6.0,
    277.0,
    184.0,
    505.0,
    fill="#09F0FF",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=293.0,
    y=466.0,
    width=41.0,
    height=32.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=209.0,
    y=466.0,
    width=41.0,
    height=32.0
)

canvas.create_text(
    47.0,
    277.0,
    anchor="nw",
    text="Order",
    fill="#0D0D0D",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    14.0,
    481.0,
    anchor="nw",
    text="Total",
    fill="#0D0C0C",
    font=("Inter", 14 * -1)
)

window.resizable(False, False)
window.mainloop()
